let data = [
  { "code": "USD", "name": "United States Dollar", "rate": 1.00, "symbol": "$", "flag": "https://flagsapi.com/US/flat/64.png" },
  { "code": "PKR", "name": "Pakistani Rupee", "rate": 278.50, "symbol": "₨", "flag": "https://flagsapi.com/PK/flat/64.png" },
  { "code": "INR", "name": "Indian Rupee", "rate": 83.30, "symbol": "₹", "flag": "https://flagsapi.com/IN/flat/64.png" },
  { "code": "EUR", "name": "Euro", "rate": 0.92, "symbol": "€", "flag": "https://flagsapi.com/EU/flat/64.png" },
  { "code": "GBP", "name": "British Pound", "rate": 0.79, "symbol": "£", "flag": "https://flagsapi.com/GB/flat/64.png" },
  { "code": "AED", "name": "UAE Dirham", "rate": 3.67, "symbol": "د.إ", "flag": "https://flagsapi.com/AE/flat/64.png" },
  { "code": "SAR", "name": "Saudi Riyal", "rate": 3.75, "symbol": "﷼", "flag": "https://flagsapi.com/SA/flat/64.png" },
  { "code": "CAD", "name": "Canadian Dollar", "rate": 1.35, "symbol": "C$", "flag": "https://flagsapi.com/CA/flat/64.png" },
  { "code": "AUD", "name": "Australian Dollar", "rate": 1.52, "symbol": "A$", "flag": "https://flagsapi.com/AU/flat/64.png" },
  { "code": "JPY", "name": "Japanese Yen", "rate": 151.40, "symbol": "¥", "flag": "https://flagsapi.com/JP/flat/64.png" },
  { "code": "CNY", "name": "Chinese Yuan", "rate": 7.23, "symbol": "¥", "flag": "https://flagsapi.com/CN/flat/64.png" },
  { "code": "TRY", "name": "Turkish Lira", "rate": 32.25, "symbol": "₺", "flag": "https://flagsapi.com/TR/flat/64.png" },
  { "code": "AFN", "name": "Afghan Afghani", "rate": 71.10, "symbol": "؋", "flag": "https://flagsapi.com/AF/flat/64.png" },
  { "code": "BDT", "name": "Bangladeshi Taka", "rate": 109.80, "symbol": "৳", "flag": "https://flagsapi.com/BD/flat/64.png" },
  { "code": "MYR", "name": "Malaysian Ringgit", "rate": 4.73, "symbol": "RM", "flag": "https://flagsapi.com/MY/flat/64.png" },
  { "code": "SGD", "name": "Singapore Dollar", "rate": 1.34, "symbol": "S$", "flag": "https://flagsapi.com/SG/flat/64.png" },
  { "code": "QAR", "name": "Qatari Rial", "rate": 3.64, "symbol": "﷼", "flag": "https://flagsapi.com/QA/flat/64.png" },
  { "code": "KWD", "name": "Kuwaiti Dinar", "rate": 0.31, "symbol": "د.ك", "flag": "https://flagsapi.com/KW/flat/64.png" },
  { "code": "OMR", "name": "Omani Rial", "rate": 0.38, "symbol": "﷼", "flag": "https://flagsapi.com/OM/flat/64.png" },
  { "code": "RUB", "name": "Russian Ruble", "rate": 92.40, "symbol": "₽", "flag": "https://flagsapi.com/RU/flat/64.png" },
  
  { "code": "BRL", "name": "Brazilian Real", "rate": 5.05, "symbol": "R$", "flag": "https://flagsapi.com/BR/flat/64.png" },
  { "code": "ZAR", "name": "South African Rand", "rate": 18.85, "symbol": "R", "flag": "https://flagsapi.com/ZA/flat/64.png" },
  { "code": "NZD", "name": "New Zealand Dollar", "rate": 1.66, "symbol": "NZ$", "flag": "https://flagsapi.com/NZ/flat/64.png" },
  { "code": "CHF", "name": "Swiss Franc", "rate": 0.90, "symbol": "CHF", "flag": "https://flagsapi.com/CH/flat/64.png" },
  { "code": "LKR", "name": "Sri Lankan Rupee", "rate": 298.50, "symbol": "Rs", "flag": "https://flagsapi.com/LK/flat/64.png" },
  { "code": "EGP", "name": "Egyptian Pound", "rate": 47.40, "symbol": "E£", "flag": "https://flagsapi.com/EG/flat/64.png" },
  { "code": "THB", "name": "Thai Baht", "rate": 36.45, "symbol": "฿", "flag": "https://flagsapi.com/TH/flat/64.png" },
  { "code": "IDR", "name": "Indonesian Rupiah", "rate": 15885, "symbol": "Rp", "flag": "https://flagsapi.com/ID/flat/64.png" },
  { "code": "KRW", "name": "South Korean Won", "rate": 1348, "symbol": "₩", "flag": "https://flagsapi.com/KR/flat/64.png" },
  { "code": "MXN", "name": "Mexican Peso", "rate": 16.55, "symbol": "$", "flag": "https://flagsapi.com/MX/flat/64.png" },
  { "code": "SEK", "name": "Swedish Krona", "rate": 10.65, "symbol": "kr", "flag": "https://flagsapi.com/SE/flat/64.png" },
  { "code": "NOK", "name": "Norwegian Krone", "rate": 10.75, "symbol": "kr", "flag": "https://flagsapi.com/NO/flat/64.png" },
  { "code": "DKK", "name": "Danish Krone", "rate": 6.88, "symbol": "kr", "flag": "https://flagsapi.com/DK/flat/64.png" },
  { "code": "IRR", "name": "Iranian Rial", "rate": 42000, "symbol": "﷼", "flag": "https://flagsapi.com/IR/flat/64.png" },
  { "code": "BHD", "name": "Bahraini Dinar", "rate": 0.38, "symbol": ".د.ب", "flag": "https://flagsapi.com/BH/flat/64.png" },
  { "code": "VND", "name": "Vietnamese Dong", "rate": 24810, "symbol": "₫", "flag": "https://flagsapi.com/VN/flat/64.png" },
  { "code": "PHP", "name": "Philippine Peso", "rate": 56.15, "symbol": "₱", "flag": "https://flagsapi.com/PH/flat/64.png" },
  { "code": "PLN", "name": "Polish Zloty", "rate": 3.98, "symbol": "zł", "flag": "https://flagsapi.com/PL/flat/64.png" },
  { "code": "ILS", "name": "Israeli Shekel", "rate": 3.65, "symbol": "₪", "flag": "https://flagsapi.com/IL/flat/64.png" },
  { "code": "JOD", "name": "Jordanian Dinar", "rate": 0.71, "symbol": "د.ا", "flag": "https://flagsapi.com/JO/flat/64.png" }
]

export default data